quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:54321/demodb
      driver: org.postgresql.Driver
    username: postgres
    password: postgres

  hibernate-orm:
    database:
      generation: none
    log:
      sql: true

  flyway:
    migrate-at-start: true
    locations: classpath:db/migration
    table: flyway_schema_history_demo

#    docker run -d \
#      --name my-postgres \
#      -e POSTGRES_USER=postgres \
#      -e POSTGRES_PASSWORD=postgres \
#      -e POSTGRES_DB=demodb \
#      -p 54321:5432 \
#      postgres:17

